Metrics/LineLength:
  Max: 99

Style/HashSyntax:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/SpaceAroundOperators:
  Enabled: false

Style/SpaceInsideBlockBraces:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Rails/TimeZone:
  Enabled: false
